// src/lib/offlineSync.ts
// Generated by assistant: offline sync implementation for Optocare EMR

import { apiClient } from "@/lib/apiClient";
import { offlineStore } from "@/lib/offlineStore";
import { toast } from "sonner";

function appointmentsQueueKey(clinicId: string) { return `appointments-queue:${clinicId}`; }
function billsQueueKey(clinicId: string) { return `bills-queue:${clinicId}`; }

export interface AppointmentQueueItem { payload?: any; queued_at?: number | string; [k:string]: any }
export interface BillQueueItem {
  clinic_id?: string;
  patient_id?: string | number;
  payer_type?: string;
  hmo_id?: string | null;
  consultation_fee?: number;
  notes?: string | null;
  items?: Array<any>;
  visit_id?: string | number | null;
  queued_at?: number | string;
  [k:string]: any;
}

function normalizeMaybePromise<T>(v: Promise<T> | T | void): Promise<T | void> { return Promise.resolve(v as any); }

async function removeQueueItemAndSave<T extends { [k:string]: any }>(key:string, queue:T[], idx:number): Promise<void> {
  queue.splice(idx,1);
  if (queue.length === 0) await normalizeMaybePromise(offlineStore.remove(key));
  else await normalizeMaybePromise(offlineStore.save(key, queue));
}

export async function processAppointmentsQueue(clinicId: string): Promise<{ success:number; failed:number }> {
  const key = appointmentsQueueKey(clinicId);
  let success = 0, failed = 0;
  try {
    const queue = (offlineStore.get<AppointmentQueueItem[]>(key) ?? []) as AppointmentQueueItem[];
    let idx = 0;
    while (idx < queue.length) {
      const item = queue[idx];
      try {
        const payload = { ...(item.payload ?? item), clinic_id: clinicId };
        const { error } = await apiClient.from("appointments").insert(payload as any);
        if (error) throw new Error(error.message);
        await removeQueueItemAndSave(key, queue, idx);
        success++;
        toast.success(`Appointment queued at ${item.queued_at ?? 'unknown'} synced`);
      } catch (err:any) {
        failed++; idx++; toast.error(`Failed to sync appointment queued at ${item.queued_at ?? 'unknown'}: ${String(err?.message ?? err)}`);
      }
    }
  } catch (err:any) {
    toast.error(`Failed reading appointments queue: ${String(err?.message ?? err)}`);
    throw err;
  }
  return { success, failed };
}

export async function processBillsQueue(clinicId: string): Promise<{ success:number; failed:number }> {
  const key = billsQueueKey(clinicId);
  let success = 0, failed = 0;
  try {
    const queue = (offlineStore.get<BillQueueItem[]>(key) ?? []) as BillQueueItem[];
    let idx = 0;
    while (idx < queue.length) {
      const item = queue[idx];
      try {
        const patientId = item.patient_id ?? null;
        if (!patientId) throw new Error('Missing patient_id on queued bill');

        // find latest visit like Billing.tsx
        const { data: latestVisit, error: lvErr } = await apiClient
          .from('visits')
          .select('id')
          .eq('clinic_id', clinicId)
          .eq('patient_id', String(patientId))
          .order('created_at', { ascending: false })
          .limit(1)
          .single();

        if (lvErr || !latestVisit) throw new Error('Complete patient visit before billing');

        const isHmo = (item.payer_type === 'hmo') || Boolean(item.hmo_id);
        const consult = Number(item.consultation_fee || 0);
        const itemsList = item.items ?? [];
        const itemsTotal = itemsList.reduce((s:any, it:any) => s + Number((it.total_price ?? (Number(it.quantity||0) * Number(it.unit_price||0))) || 0), 0);
        const grandTotal = itemsTotal + consult;

        const { data: bill, error: billErr } = await apiClient.from('billing').insert({
          clinic_id: clinicId,
          patient_id: patientId,
          visit_id: latestVisit?.id,
          payer_type: isHmo ? 'hmo' : 'private',
          hmo_id: isHmo ? item.hmo_id ?? null : null,
          consultation_fee: consult,
          notes: item.notes ?? null,
          status: 'pending',
        } as any).select().single();

        if (billErr || !bill) throw new Error(billErr?.message || 'Failed to create billing record');
        const billingId = (bill as any).id;

        if (itemsList.length > 0) {
          const payload = itemsList.map((it:any) => ({
            clinic_id: clinicId,
            billing_id: billingId,
            item_type: it.item_type ?? 'Item',
            item_name: it.item_name || it.item_type || 'Item',
            quantity: it.quantity,
            unit_price: it.unit_price,
            total_price: it.total_price ?? (Number(it.quantity||0) * Number(it.unit_price||0)),
          }));

          const { error: itemsErr } = await apiClient.from('billing_items').insert(payload as any);
          if (itemsErr) throw new Error(itemsErr.message);
        }

        if (isHmo && item.hmo_id) {
          let hmoName = '';
          try {
            const { data: hmoRow } = await apiClient.from('hmos').select('name').eq('clinic_id', clinicId).eq('id', item.hmo_id).maybeSingle();
            if (hmoRow) hmoName = hmoRow.name ?? '';
          } catch {}

          await apiClient.from('hmo_claims').insert({
            clinic_id: clinicId,
            billing_id: billingId,
            hmo_id: item.hmo_id,
            hmo_name: hmoName,
            patient_id: patientId,
            service_cost: grandTotal,
            approved_amount: 0,
            co_payment: 0,
            status: 'Pending',
          } as any);
        }

        // inventory deductions (best-effort)
        for (const it of itemsList) {
          const name = (it.item_name || it.item_type || '').trim();
          if (!name) continue;
          try {
            const { data: stock, error: findErr } = await apiClient.from('inventory').select('id, stock_quantity').eq('clinic_id', clinicId).ilike('name', name).maybeSingle();
            if (findErr) { toast.error(`Inventory lookup failed for "${name}": ${findErr.message}`); continue; }
            if (!stock) { toast.error(`Inventory item not found: ${name}`); continue; }
            const currentQty = Number(stock.stock_quantity) || 0;
            const billedQty = Number(it.quantity || 0);
            const nextQty = Math.max(currentQty - billedQty, 0);
            const { error: stockErr } = await apiClient.from('inventory').update({ stock_quantity: nextQty }).eq('id', stock.id);
            if (stockErr) { toast.error(`Inventory update failed for "${name}": ${stockErr.message}`); continue; }
          } catch (invErr) { toast.error(`Inventory deduction error for "${it.item_name ?? it.item_type}": ${String(invErr)}`); }
        }

        // remove item on full success
        await removeQueueItemAndSave(key, queue, idx);
        success++;
        toast.success(`Bill queued at ${item.queued_at ?? 'unknown'} synced (bill ${String(billingId)})`);
      } catch (err:any) {
        failed++; idx++; toast.error(`Failed to sync bill queued at ${item.queued_at ?? 'unknown'}: ${String(err?.message ?? err)}`);
      }
    }
  } catch (err:any) {
    toast.error(`Failed reading bills queue: ${String(err?.message ?? err)}`);
    throw err;
  }
  return { success, failed };
}

let _syncRunning = false;
export async function runOfflineSync(clinicId: string): Promise<void> {
  if (_syncRunning) return;
  _syncRunning = true;
  try {
    toast.info('Offline sync started');
    await processAppointmentsQueue(clinicId);
    await processBillsQueue(clinicId);
    toast.success('Offline sync completed');
    if (typeof window !== 'undefined' && typeof CustomEvent !== 'undefined') {
      window.dispatchEvent(new CustomEvent('optocare:sync:done', { detail: { clinicId } }));
    }
  } catch (err:any) {
    toast.error(`Offline sync failed: ${String(err?.message ?? err)}`);
  } finally { _syncRunning = false; }
}

export function registerAutomaticSync(clinicId: string, opts?: { debounceMs?: number; autoTriggerIfOnline?: boolean }) {
  const debounceMs = opts?.debounceMs ?? 1000; const autoTrigger = opts?.autoTriggerIfOnline ?? true; let timer:any = null;
  function onOnline() { if (timer) clearTimeout(timer); timer = setTimeout(() => { runOfflineSync(clinicId).catch((e)=>console.error('runOfflineSync error', e)); }, debounceMs); }
  if (typeof window !== 'undefined' && 'addEventListener' in window) {
    window.addEventListener('online', onOnline);
    if (autoTrigger && typeof navigator !== 'undefined' && navigator.onLine) onOnline();
  }
  return { trigger: () => runOfflineSync(clinicId), unregister: () => { if (typeof window !== 'undefined' && 'removeEventListener' in window) window.removeEventListener('online', onOnline); if (timer) clearTimeout(timer); } };
}
