// src/lib/offlineSync.ts
// Generated by assistant: offline sync implementation for Optocare EMR

import { apiClient } from "@/lib/apiClient";
import { offlineStore } from "@/lib/offlineStore";
import { toast } from "sonner";
import { getOfflineOperations, removeOfflineOperation, markOfflineOperationFailed } from "@/lib/offlineEngine";

function appointmentsQueueKey(clinicId: string) { return `appointments-queue:${clinicId}`; }
function billsQueueKey(clinicId: string) { return `bills-queue:${clinicId}`; }

export interface AppointmentQueueItem { payload?: any; queued_at?: number | string; [k:string]: any }
export interface BillQueueItem {
  clinic_id?: string;
  patient_id?: string | number;
  payer_type?: string;
  hmo_id?: string | null;
  consultation_fee?: number;
  notes?: string | null;
  items?: Array<any>;
  visit_id?: string | number | null;
  discount_amount?: number;
  discount_reason?: string | null;
  discount_applied_by?: string | null;
  billing_scope?: string;
  family_id?: string | null;
  editing_billing_id?: string | null; // NEW: if set, update existing billing record instead of creating
  queued_at?: number | string;
  [k:string]: any;
}

function normalizeMaybePromise<T>(v: Promise<T> | T | void): Promise<T | void> { return Promise.resolve(v as any); }

async function removeQueueItemAndSave<T extends { [k:string]: any }>(key:string, queue:T[], idx:number): Promise<void> {
  queue.splice(idx,1);
  if (queue.length === 0) await normalizeMaybePromise(offlineStore.remove(key));
  else await normalizeMaybePromise(offlineStore.save(key, queue));
}

export async function processCoreOfflineOperations(clinicId: string): Promise<{ success: number; failed: number }> {
  const operations = await getOfflineOperations(clinicId);
  let success = 0, failed = 0;

  for (const operation of operations) {
    try {
      if (operation.kind === "family.create") {
        const { error } = await apiClient.from("families").upsert(operation.payload as any, { onConflict: "id" });
        if (error) throw new Error(error.message);
      } else if (operation.kind === "patient.create") {
        const { error } = await apiClient.from("patients").upsert(operation.payload as any, { onConflict: "id" });
        if (error) throw new Error(error.message);
      } else if (operation.kind === "visit.save") {
        const payload = { ...(operation.payload as any) };
        const { error } = await apiClient.from("visits").upsert(payload, { onConflict: "id" });
        if (error) throw new Error(error.message);
      } else if (operation.kind === "appointment.save") {
        const { error } = await apiClient.from("appointments").upsert(operation.payload as any, { onConflict: "id" });
        if (error) throw new Error(error.message);
      } else if (operation.kind === "appointment.status") {
        const payload = operation.payload as any;
        const { error } = await apiClient.from("appointments").update({ status: payload.status }).eq("clinic_id", clinicId).eq("id", operation.entityId);
        if (error) throw new Error(error.message);
      } else if (operation.kind === "inventory.save") {
        const { error } = await apiClient.from("inventory").upsert(operation.payload as any, { onConflict: "id" });
        if (error) throw new Error(error.message);
      } else if (operation.kind === "inventory.delete") {
        const { error } = await apiClient.from("inventory").delete().eq("clinic_id", clinicId).eq("id", operation.entityId);
        if (error) throw new Error(error.message);
      } else if (operation.kind === "inventory.sale") {
        const payload = operation.payload as any;
        const { data: existingSale } = await apiClient.from("inventory_sales").select("id").eq("id", operation.entityId).maybeSingle();
        if (!existingSale) {
          const { error: saleError } = await apiClient.from("inventory_sales").insert(payload.sale);
          if (saleError) throw new Error(saleError.message);
          const { error: itemError } = await apiClient.from("inventory_sale_items").insert(payload.items);
          if (itemError) throw new Error(itemError.message);
        }
      } else if (operation.kind === "payment.create") {
        const payload = operation.payload as any;
        const { data: existingPayment } = await apiClient.from("payments").select("id").eq("id", operation.entityId).eq("clinic_id", clinicId).maybeSingle();
        if (!existingPayment) {
          const { error } = await apiClient.from("payments").insert({ ...payload, id: operation.entityId, clinic_id: clinicId });
          if (error) throw new Error(error.message);
        }
        const { error: recalcError } = await apiClient.rpc("recalculate_billing_totals", { p_billing_id: payload.billing_id });
        if (recalcError) throw new Error(recalcError.message);
      }
      await removeOfflineOperation(clinicId, operation.id);
      success++;
    } catch (error) {
      failed++;
      await markOfflineOperationFailed(clinicId, operation, error);
      // Stop here when the first dependency fails; later operations may depend on it.
      break;
    }
  }

  return { success, failed };
}

export async function processAppointmentsQueue(clinicId: string): Promise<{ success:number; failed:number }> {
  const key = appointmentsQueueKey(clinicId);
  let success = 0, failed = 0;
  try {
    const queue = (offlineStore.get<AppointmentQueueItem[]>(key) ?? []) as AppointmentQueueItem[];
    let idx = 0;
    while (idx < queue.length) {
      const item = queue[idx];
      try {
        const payload = { ...(item.payload ?? item), clinic_id: clinicId };
        const { error } = await apiClient.from("appointments").insert(payload as any);
        if (error) throw new Error(error.message);
        await removeQueueItemAndSave(key, queue, idx);
        success++;
        toast.success(`Appointment queued at ${item.queued_at ?? 'unknown'} synced`);
      } catch (err:any) {
        failed++; idx++; toast.error(`Failed to sync appointment queued at ${item.queued_at ?? 'unknown'}: ${String(err?.message ?? err)}`);
      }
    }
  } catch (err:any) {
    toast.error(`Failed reading appointments queue: ${String(err?.message ?? err)}`);
    throw err;
  }
  return { success, failed };
}

export async function processBillsQueue(clinicId: string): Promise<{ success:number; failed:number }> {
  const key = billsQueueKey(clinicId);
  let success = 0, failed = 0;
  try {
    const queue = (offlineStore.get<BillQueueItem[]>(key) ?? []) as BillQueueItem[];
    let idx = 0;
    while (idx < queue.length) {
      const item = queue[idx];
      try {
        const patientId = item.patient_id ?? null;
        if (!patientId) throw new Error('Missing patient_id on queued bill');

        // find latest visit like Billing.tsx
        let latestVisit: any = null;
        if (item.visit_id) {
          const { data, error } = await apiClient.from('visits').select('id').eq('clinic_id', clinicId).eq('id', String(item.visit_id)).maybeSingle();
          if (error) throw new Error(error.message);
          latestVisit = data;
        } else {
          const { data, error: lvErr } = await apiClient
            .from('visits')
            .select('id')
            .eq('clinic_id', clinicId)
            .eq('patient_id', String(patientId))
            .order('created_at', { ascending: false })
            .limit(1)
            .single();
          if (lvErr) throw new Error(lvErr.message);
          latestVisit = data;
        }

        if (!latestVisit) throw new Error('Complete patient visit before billing');

        const isHmo = (item.payer_type === 'hmo') || Boolean(item.hmo_id);
        const consult = Number(item.consultation_fee || 0);
        const itemsList = item.items ?? [];
        const itemsTotal = itemsList.reduce((s:any, it:any) => s + Number((it.total_price ?? (Number(it.quantity||0) * Number(it.unit_price||0))) || 0), 0);
        const discount = Math.max(0, Math.min(Number(item.discount_amount || 0), itemsTotal + consult));
        const grandTotal = Math.max(0, itemsTotal + consult - discount);

        let billingId: string;

        // NEW: Check if this is an editing operation
        if (item.editing_billing_id) {
          // Update existing billing record
          billingId = item.editing_billing_id;

          const updatePayload: any = {
            consultation_fee: consult,
            discount_amount: discount,
            discount_reason: item.discount_reason ?? null,
            discount_applied_by: item.discount_applied_by ?? null,
            billing_scope: item.billing_scope ?? 'individual',
            family_id: item.family_id ?? null,
            notes: item.notes ?? null,
            payer_type: isHmo ? 'hmo' : 'private',
          };

          if (isHmo) {
            updatePayload.hmo_id = item.hmo_id ?? null;
          }

          const { error: updateErr } = await apiClient
            .from('billing')
            .update(updatePayload)
            .eq('id', billingId);

          if (updateErr) throw new Error(`Failed to update billing: ${updateErr.message}`);
        } else {
          const { data: existingBill } = await apiClient
            .from('billing')
            .select('id')
            .eq('clinic_id', clinicId)
            .eq('visit_id', latestVisit.id)
            .maybeSingle();

          if (existingBill) {
            billingId = (existingBill as any).id;
          } else {
          // Create new billing record (original behavior)
          const { data: bill, error: billErr } = await apiClient.from('billing').insert({
            clinic_id: clinicId,
            patient_id: patientId,
            visit_id: latestVisit?.id,
            payer_type: isHmo ? 'hmo' : 'private',
            hmo_id: isHmo ? item.hmo_id ?? null : null,
            consultation_fee: consult,
            discount_amount: discount,
            discount_reason: item.discount_reason ?? null,
            discount_applied_by: item.discount_applied_by ?? null,
            billing_scope: item.billing_scope ?? 'individual',
            family_id: item.family_id ?? null,
            notes: item.notes ?? null,
            status: 'pending',
          } as any).select().single();

          if (billErr || !bill) throw new Error(billErr?.message || 'Failed to create billing record');
          billingId = (bill as any).id;
          }
        }

        // Insert billing items (always insert new items, never update)
        if (itemsList.length > 0) {
          const payload = itemsList.map((it:any) => ({
            clinic_id: clinicId,
            billing_id: billingId,
            item_type: it.item_type ?? 'Item',
            item_name: it.item_name || it.item_type || 'Item',
            quantity: it.quantity,
            unit_price: it.unit_price,
            total_price: it.total_price ?? (Number(it.quantity||0) * Number(it.unit_price||0)),
          }));

          const { error: itemsErr } = await apiClient.from('billing_items').insert(payload as any);
          if (itemsErr) throw new Error(itemsErr.message);
        }

        // NEW: Only create HMO claim if not already exists for this billing_id
        if (isHmo && item.hmo_id) {
          let hmoName = '';
          try {
            const { data: hmoRow } = await apiClient.from('hmos').select('name').eq('clinic_id', clinicId).eq('id', item.hmo_id).maybeSingle();
            if (hmoRow) hmoName = hmoRow.name ?? '';
          } catch {}

          // Check if claim already exists
          const { data: existingClaim } = await apiClient
            .from('hmo_claims')
            .select('id')
            .eq('billing_id', billingId)
            .maybeSingle();

          if (!existingClaim) {
            await apiClient.from('hmo_claims').insert({
              clinic_id: clinicId,
              billing_id: billingId,
              hmo_id: item.hmo_id,
              hmo_name: hmoName,
              patient_id: patientId,
              service_cost: grandTotal,
              approved_amount: 0,
              co_payment: 0,
              status: 'Pending',
            } as any);
          }
        }

        // inventory deductions (best-effort)
        for (const it of itemsList) {
          const name = (it.item_name || it.item_type || '').trim();
          if (!name) continue;
          try {
            const { data: stock, error: findErr } = await apiClient.from('inventory').select('id, stock_quantity').eq('clinic_id', clinicId).ilike('name', name).maybeSingle();
            if (findErr) { toast.error(`Inventory lookup failed for "${name}": ${findErr.message}`); continue; }
            if (!stock) { toast.error(`Inventory item not found: ${name}`); continue; }
            const currentQty = Number(stock.stock_quantity) || 0;
            const billedQty = Number(it.quantity || 0);
            const nextQty = Math.max(currentQty - billedQty, 0);
            const { error: stockErr } = await apiClient.from('inventory').update({ stock_quantity: nextQty }).eq('id', stock.id);
            if (stockErr) { toast.error(`Inventory update failed for "${name}": ${stockErr.message}`); continue; }
          } catch (invErr) { toast.error(`Inventory deduction error for "${it.item_name ?? it.item_type}": ${String(invErr)}`); }
        }

        // remove item on full success
        await removeQueueItemAndSave(key, queue, idx);
        success++;
        const action = item.editing_billing_id ? 'updated' : 'created';
        toast.success(`Bill queued at ${item.queued_at ?? 'unknown'} synced (bill ${action}: ${String(billingId)})`);
      } catch (err:any) {
        failed++; idx++; toast.error(`Failed to sync bill queued at ${item.queued_at ?? 'unknown'}: ${String(err?.message ?? err)}`);
      }
    }
  } catch (err:any) {
    toast.error(`Failed reading bills queue: ${String(err?.message ?? err)}`);
    throw err;
  }
  return { success, failed };
}

let _syncRunning = false;
export async function runOfflineSync(clinicId: string): Promise<void> {
  if (_syncRunning) return;
  _syncRunning = true;
  try {
    toast.info('Offline sync started');
    await processCoreOfflineOperations(clinicId);
    await processAppointmentsQueue(clinicId);
    await processBillsQueue(clinicId);
    toast.success('Offline sync completed');
    if (typeof window !== 'undefined' && typeof CustomEvent !== 'undefined') {
      window.dispatchEvent(new CustomEvent('optocare:sync:done', { detail: { clinicId } }));
    }
  } catch (err:any) {
    toast.error(`Offline sync failed: ${String(err?.message ?? err)}`);
  } finally { _syncRunning = false; }
}

export function registerAutomaticSync(clinicId: string, opts?: { debounceMs?: number; autoTriggerIfOnline?: boolean }) {
  const debounceMs = opts?.debounceMs ?? 1000; const autoTrigger = opts?.autoTriggerIfOnline ?? true; let timer:any = null;
  function onOnline() { if (timer) clearTimeout(timer); timer = setTimeout(() => { runOfflineSync(clinicId).catch((e)=>console.error('runOfflineSync error', e)); }, debounceMs); }
  if (typeof window !== 'undefined' && 'addEventListener' in window) {
    window.addEventListener('online', onOnline);
    if (autoTrigger && typeof navigator !== 'undefined' && navigator.onLine) onOnline();
  }
  return { trigger: () => runOfflineSync(clinicId), unregister: () => { if (typeof window !== 'undefined' && 'removeEventListener' in window) window.removeEventListener('online', onOnline); if (timer) clearTimeout(timer); } };
}
