project_id = "avogfzqizuusqzjivhqj"

[functions.validate-invite]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-daily-summary]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false
