project_id = "avogfzqizuusqzjivhqj"

[functions.validate-invite]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-daily-summary]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = false

[functions.send-billing-reminder]
verify_jwt = false
