-- Harden tenant ownership for feedback, recall, communication, HMO history,
-- verification, medication dispensing, and appointment reminder records.
create unique index if not exists appointments_id_clinic_unique on public.appointments(id,clinic_id);
create unique index if not exists feedback_requests_id_clinic_unique on public.feedback_requests(id,clinic_id);
create unique index if not exists feedback_responses_id_clinic_unique on public.feedback_responses(id,clinic_id);
create unique index if not exists feedback_followups_id_clinic_unique on public.feedback_followups(id,clinic_id);
create unique index if not exists patient_recalls_id_clinic_unique on public.patient_recalls(id,clinic_id);
create unique index if not exists patient_recall_events_id_clinic_unique on public.patient_recall_events(id,clinic_id);
create unique index if not exists patient_communications_id_clinic_unique on public.patient_communications(id,clinic_id);
create unique index if not exists hmo_history_id_clinic_unique on public.hmo_history(id,clinic_id);
create unique index if not exists hmo_verification_log_id_clinic_unique on public.hmo_verification_log(id,clinic_id);
create unique index if not exists appointment_reminders_id_clinic_unique on public.appointment_reminders(id,clinic_id);

alter table public.feedback_requests drop constraint if exists feedback_requests_patient_id_clinic_fkey;
alter table public.feedback_requests add constraint feedback_requests_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.feedback_requests drop constraint if exists feedback_requests_visit_id_clinic_fkey;
alter table public.feedback_requests add constraint feedback_requests_visit_id_clinic_fkey foreign key(visit_id,clinic_id) references public.visits(id,clinic_id);
alter table public.feedback_responses drop constraint if exists feedback_responses_patient_id_clinic_fkey;
alter table public.feedback_responses add constraint feedback_responses_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.feedback_responses drop constraint if exists feedback_responses_visit_id_clinic_fkey;
alter table public.feedback_responses add constraint feedback_responses_visit_id_clinic_fkey foreign key(visit_id,clinic_id) references public.visits(id,clinic_id);
alter table public.feedback_responses drop constraint if exists feedback_responses_request_id_clinic_fkey;
alter table public.feedback_responses add constraint feedback_responses_request_id_clinic_fkey foreign key(feedback_request_id,clinic_id) references public.feedback_requests(id,clinic_id);
alter table public.feedback_followups drop constraint if exists feedback_followups_patient_id_clinic_fkey;
alter table public.feedback_followups add constraint feedback_followups_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.feedback_followups drop constraint if exists feedback_followups_visit_id_clinic_fkey;
alter table public.feedback_followups add constraint feedback_followups_visit_id_clinic_fkey foreign key(visit_id,clinic_id) references public.visits(id,clinic_id);
alter table public.feedback_followups drop constraint if exists feedback_followups_request_id_clinic_fkey;
alter table public.feedback_followups add constraint feedback_followups_request_id_clinic_fkey foreign key(feedback_request_id,clinic_id) references public.feedback_requests(id,clinic_id);
alter table public.feedback_followups drop constraint if exists feedback_followups_response_id_clinic_fkey;
alter table public.feedback_followups add constraint feedback_followups_response_id_clinic_fkey foreign key(feedback_response_id,clinic_id) references public.feedback_responses(id,clinic_id);
alter table public.patient_recalls drop constraint if exists patient_recalls_patient_id_clinic_fkey;
alter table public.patient_recalls add constraint patient_recalls_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.patient_recalls drop constraint if exists patient_recalls_source_visit_id_clinic_fkey;
alter table public.patient_recalls add constraint patient_recalls_source_visit_id_clinic_fkey foreign key(source_visit_id,clinic_id) references public.visits(id,clinic_id);
alter table public.patient_recall_events drop constraint if exists patient_recall_events_patient_id_clinic_fkey;
alter table public.patient_recall_events add constraint patient_recall_events_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.patient_recall_events drop constraint if exists patient_recall_events_visit_id_clinic_fkey;
alter table public.patient_recall_events add constraint patient_recall_events_visit_id_clinic_fkey foreign key(visit_id,clinic_id) references public.visits(id,clinic_id);
alter table public.patient_communications drop constraint if exists patient_communications_patient_id_clinic_fkey;
alter table public.patient_communications add constraint patient_communications_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.patient_communications drop constraint if exists patient_communications_visit_id_clinic_fkey;
alter table public.patient_communications add constraint patient_communications_visit_id_clinic_fkey foreign key(visit_id,clinic_id) references public.visits(id,clinic_id);
alter table public.hmo_history drop constraint if exists hmo_history_patient_id_clinic_fkey;
alter table public.hmo_history add constraint hmo_history_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.hmo_verification_log drop constraint if exists hmo_verification_log_patient_id_clinic_fkey;
alter table public.hmo_verification_log add constraint hmo_verification_log_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.hmo_verification_log drop constraint if exists hmo_verification_log_hmo_id_clinic_fkey;
alter table public.hmo_verification_log add constraint hmo_verification_log_hmo_id_clinic_fkey foreign key(hmo_id,clinic_id) references public.hmos(id,clinic_id);
alter table public.visit_medication_dispensing drop constraint if exists visit_medication_dispensing_visit_id_clinic_fkey;
alter table public.visit_medication_dispensing add constraint visit_medication_dispensing_visit_id_clinic_fkey foreign key(visit_id,clinic_id) references public.visits(id,clinic_id);
alter table public.visit_medication_dispensing drop constraint if exists visit_medication_dispensing_patient_id_clinic_fkey;
alter table public.visit_medication_dispensing add constraint visit_medication_dispensing_patient_id_clinic_fkey foreign key(patient_id,clinic_id) references public.patients(id,clinic_id);
alter table public.visit_medication_dispensing drop constraint if exists visit_medication_dispensing_inventory_id_clinic_fkey;
alter table public.visit_medication_dispensing add constraint visit_medication_dispensing_inventory_id_clinic_fkey foreign key(inventory_id,clinic_id) references public.inventory(id,clinic_id);
alter table public.appointment_reminders drop constraint if exists appointment_reminders_appointment_id_clinic_fkey;
alter table public.appointment_reminders add constraint appointment_reminders_appointment_id_clinic_fkey foreign key(appointment_id,clinic_id) references public.appointments(id,clinic_id);
