// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseAccessGateState, waitForSupabaseAccessGate } from '@/lib/supabase-access-gate';

const SUPABASE_URL = "https://avogfzqizuusqzjivhqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2b2dmenFpenV1c3F6aml2aHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5OTQ0MTgsImV4cCI6MjA5MDU3MDQxOH0._mQQxxm-raT1p_fqowfQu65Tww_8nLduDuYJBKyzo2U";
const SHARED_CLIENT_HEADER = 'x-optocare-shared-client';
const RETRY_HEADER = 'x-auth-retried';

type GlobalWithSupabaseSingleton = typeof globalThis & {
  __optocareSupabaseClient?: SupabaseClient<Database>;
  __optocareSupabaseBypassPatchInstalled?: boolean;
};

const sharedGlobal = globalThis as GlobalWithSupabaseSingleton;
const originalFetch = globalThis.fetch.bind(globalThis);

let sharedClient = sharedGlobal.__optocareSupabaseClient;

function getRequestUrl(input: RequestInfo | URL) {
  return typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
}

function getRequestMethod(input: RequestInfo | URL, init?: RequestInit) {
  if (init?.method) return init.method.toUpperCase();
  if (typeof Request !== 'undefined' && input instanceof Request) return input.method.toUpperCase();
  return 'GET';
}

function mergeHeaders(input: RequestInfo | URL, init?: RequestInit) {
  const headers = new Headers(typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
  const nextHeaders = new Headers(init?.headers);
  nextHeaders.forEach((value, key) => headers.set(key, value));
  return headers;
}

function getRequestPath(url: string) {
  return url.startsWith(SUPABASE_URL) ? url.slice(SUPABASE_URL.length) : url;
}

function isSupabaseRequest(input: RequestInfo | URL) {
  return getRequestUrl(input).startsWith(SUPABASE_URL);
}

function isUnauthorizedResponse(response: Response) {
  return response.status === 401 || response.status === 403;
}

function isAuthRequest(url: string) {
  return url.includes('/auth/v1/');
}

function isBootstrapAccessRequest(url: string) {
  return url.includes('/rest/v1/profiles') || url.includes('/rest/v1/user_roles') || url.includes('/rest/v1/clinics');
}

function resolveCallerModule() {
  const stack = new Error().stack?.split('\n') ?? [];

  for (const line of stack) {
    if (line.includes('node_modules') || line.includes('@supabase') || line.includes('src/integrations/supabase/client.ts')) {
      continue;
    }

    const match = line.match(/(?:https?:\/\/[^\s)]+\/)?(src\/[^\s):?]+\.(?:ts|tsx|js|jsx))(?:\?[^\s):]*)?(?::\d+:\d+)?/);
    if (match?.[1]) return match[1];
  }

  return 'unknown';
}

async function refreshSessionOnce() {
  const { data, error } = await sharedClient!.auth.refreshSession();
  // eslint-disable-next-line no-console
  console.debug('[auth:refresh]', { ok: !error, user_id: data.session?.user?.id ?? null, error: error?.message ?? null });
  return { data, error };
}

async function gatedSupabaseFetch(input: RequestInfo | URL, init?: RequestInit) {
  const url = getRequestUrl(input);
  const method = getRequestMethod(input, init);
  const moduleName = resolveCallerModule();
  const path = getRequestPath(url);
  const currentHeaders = mergeHeaders(input, init);
  currentHeaders.set(SHARED_CLIENT_HEADER, '1');

  const initialGate = getSupabaseAccessGateState();
  const authRequest = isAuthRequest(url);
  const bootstrapAccessRequest = isBootstrapAccessRequest(url);

  // eslint-disable-next-line no-console
  console.debug('[supabase:request]', {
    module: moduleName,
    method,
    path,
    sharedClient: true,
    accessReady: initialGate.accessReady,
    hasSession: initialGate.hasSession,
    sessionBootstrapped: initialGate.sessionBootstrapped,
  });

  if (!authRequest && !initialGate.sessionBootstrapped) {
    // eslint-disable-next-line no-console
    console.debug('[auth:gate:wait]', { module: moduleName, method, path, reason: 'session_bootstrap_pending' });
    await waitForSupabaseAccessGate();
  } else if (!authRequest && !bootstrapAccessRequest && initialGate.hasSession && !initialGate.accessReady) {
    // eslint-disable-next-line no-console
    console.debug('[auth:gate:wait]', { module: moduleName, method, path, reason: 'access_hydration_pending' });
    await waitForSupabaseAccessGate();
  }

  const response = await originalFetch(input, { ...init, headers: currentHeaders });
  if (!isUnauthorizedResponse(response)) {
    return response;
  }

  const currentGate = getSupabaseAccessGateState();
  // eslint-disable-next-line no-console
  console.warn('[api:auth]', {
    module: moduleName,
    method,
    path,
    status: response.status,
    sharedClient: true,
    accessReady: currentGate.accessReady,
    hasSession: currentGate.hasSession,
    sessionBootstrapped: currentGate.sessionBootstrapped,
  });

  const retried = currentHeaders.get(RETRY_HEADER) === '1';
  if (retried || authRequest || !currentGate.hasSession) {
    return response;
  }

  const { error } = await refreshSessionOnce();
  if (error) {
    await sharedClient!.auth.signOut();
    return response;
  }

  currentHeaders.set(RETRY_HEADER, '1');
  const retryResponse = await originalFetch(input, { ...init, headers: currentHeaders });
  if (isUnauthorizedResponse(retryResponse)) {
    await sharedClient!.auth.signOut();
  }
  return retryResponse;
}

function installBypassDetection() {
  if (sharedGlobal.__optocareSupabaseBypassPatchInstalled) return;

  globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
    if (!isSupabaseRequest(input)) {
      return originalFetch(input, init);
    }

    const headers = mergeHeaders(input, init);
    if (headers.get(SHARED_CLIENT_HEADER) !== '1') {
      // eslint-disable-next-line no-console
      console.warn('[supabase:bypass]', {
        module: resolveCallerModule(),
        method: getRequestMethod(input, init),
        path: getRequestPath(getRequestUrl(input)),
        sharedClient: false,
        accessReady: getSupabaseAccessGateState().accessReady,
      });

      return gatedSupabaseFetch(input, init);
    }

    return originalFetch(input, init);
  };

  sharedGlobal.__optocareSupabaseBypassPatchInstalled = true;
}

if (!sharedClient) {
  sharedClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: gatedSupabaseFetch,
      headers: {
        [SHARED_CLIENT_HEADER]: '1',
      },
    },
  });

  sharedGlobal.__optocareSupabaseClient = sharedClient;
}

installBypassDetection();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = sharedClient;